version: "3.8"

services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379 # 서버 배포에선 ports 숨겨서 내부 전용 권장.
    command: ["redis-server","--appendonly","yes"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  refood-server:
    image: refood-server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 8080:8080
