spring:
  application:
    name: IITP

  config:
    activate:
      on-profile: local

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        generate_statistics: false
        dialect: org.hibernate.dialect.H2Dialect
    show-sql: true
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
  paths-to-match:
    - /api/**
  packages-to-scan:
    - com.iitp

cloud:
  aws:
    s3:
      bucket: ${BUCKET} # 버킷 이름
    stack.auto: false
    region.static: ${REGION} # 버킷 리전
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}