spring:
  application:
    name: IITP

  # 최대 파일 사이즈 설정
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 35MB

  # 메일 설정
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        transport:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
      default-encoding: utf-8

  # 레디스 설정
  data:
    redis:
      host: localhost
      port: 6379

# 스웨거 설정
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
  paths-to-match:
    - /api/**
  packages-to-scan:
    - com.iitp