spring:
  application:
    name: IITP

  # .env import
  config:
    import: optional:file:.env[.properties]

  # 최대 파일 사이즈 설정
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 35MB

  # OAuth
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            scope: profile_nickname, account_email
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  # 메일 설정
  mail:
    host: smtp.gmail.com  # Gmail SMTP 서버
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
        mime:
          charset: UTF-8
    default-encoding: UTF-8

  # 레디스 설정
  data:
    redis:
      host: localhost
      port: 6379

kakao:
  api:
    key: ${KAKAO_GEO_API_KEY}
    user-info-url: https://kapi.kakao.com/v2/user/me
  rest-api-key: ${KAKAO_REST_API_KEY}

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}

# 사업자 승인 관련 설정
business:
  approval:
    base-url: ${BUSINESS_APPROVAL_BASE_URL}

# CORS 설정
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:8080
    - http://127.0.0.1:3000
    - http://127.0.0.1:8080

# 스웨거 설정
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    display-request-duration: true
  paths-to-match:
    - /api/**
  packages-to-scan:
    - com.iitp


cloud:
  aws:
    s3:
      bucket: ${AWS_S3_BUCKET} # 버킷 이름
    stack.auto: false
    region.static: ${AWS_REGION} # 버킷 리전
    credentials:
      access-key: ${AWS_IAM_ACCESS_KEY}
      secret-key: ${AWS_IAM_SECRET_KEY}


